name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        PLATFORM:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        NODE:
          - 12.x
          - 10.x
          - '8.12.0'
        NODE_MIRROR:
          - 'https://npm.taobao.org/mirrors/node'
          - 'https://nodejs.org/dist'

    name: ${{matrix.NODE_MIRROR}}@${{ matrix.PLATFORM }}/${{ matrix.NODE }}

    runs-on: ${{ matrix.PLATFORM }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.NODE }}

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: node test.js ${{ matrix.NODE_MIRROR }}
